apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shoppingcartservice
  name: shoppingcartservice
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcartservice
  template:
    metadata:
      labels:
        app: shoppingcartservice
    spec:
      containers:
        - name: shoppingcartservice
          image: docker.io/patriknw/shopping-cart-service-scala:0.2-2-50bb15e4  
          # remove for real clusters, useful for minikube
          #imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: "300m"
              memory: 128Mi
